version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - ${WEB_PORT:-443}:443
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/localhost.pem:/etc/nginx/conf.d/localhost.pem
      - ./infra/nginx/localhost-key.pem:/etc/nginx/conf.d/localhost-key.pem
    working_dir: /data

  # 追記
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store:
