<?php
return [
    'SLACK_CLIENT_ID' => env('SLACK_CLIENT_ID'),
    'SLACK_CLIENT_SECRET' => env('SLACK_CLIENT_SECRET'),
    'SLACK_REDIRECT_URI' => env('SLACK_REDIRECT_URI'),
    'SLACK_API_URI' => env('SLACK_API_URI'),
];
